apiVersion: v1
kind: Pod
metadata:
  name: covid-warehouse
spec:
  restartPolicy: Never
  containers:
    - name: etl
      image: localhost/covid-warehouse:latest
      volumeMounts:
        - mountPath: /data/out
          name: out-pvc
        - mountPath: /data/in
          name: in-pvc
  volumes:
    - name: out-pvc
      persistentVolumeClaim:
        claimName: out
    - name: in-pvc
      persistentVolumeClaim:
        claimName: in
